export const C = {
    waves: {
        alpha: 0.3,
        overlap: true,
        spacing: 100,
        highMin: 90,
        highMax: 150,
        lowMin: 30,
        lowMax: 50,
        peakMin: 2,
        peakMax: 5,
        peakWidth: 150,
        chaikinTimes: 3,
        regenerate: true,
    },
    strokes: {
        density: { x: 7, y: 10 },
        noiseScale: { x: 0.156, y: 0.076 },
        moveAmtBot: { x: 28, y: 12 },
        moveAmtTop: { x: 3, y: 1 },
        steps: 4,
        stepLen: 10,
        blendAngleAmt: 1,
        flattenAngle: 0,
        strokeWidth: 10,
        taper: 0.4,
        taperLen: 25,
        taperType: 'end' as 'symmetric' | 'end',
        regenerate: true,
    },
    animation: {
        animated: false,
        jitterRatio: 3,
        clumpAmt: 150,
        clumpScale: 0.15,
        strokesPerFrame: 100,
        rowStagger: 0.5,
        direction: 'up' as 'up' | 'down',
    },
    colors: {
        hue: 250,
        addHue: 180,
        lessSaturated: false,
        regenerate: true,
    },
}

export type WavyBumpsConfig = typeof C
