import { WavyBumpsConfig } from './_wavy-bumps-types'

export const C: WavyBumpsConfig = {
    inputs: {
        colorShift: 'random',
        bumpsTendency: 'random',
        fieldType: 'random',
    },
    custom: {
        colors: false,
        waves: false,
        strokes: false,
        animation: false,
    },
    waves: {
        alpha: 0.3,
        overlap: true,
        spacing: 100,
        highMin: 90,
        highMax: 150,
        lowMin: 30,
        lowMax: 50,
        peakMin: 2,
        peakMax: 5,
        peakWidth: 150,
        chaikinTimes: 3,
    },
    strokes: {
        density: { x: 7, y: 10 },
        noiseScale: { x: 0.156, y: 0.076 },
        moveAmtBot: { x: 28, y: 12 },
        moveAmtTop: { x: 3, y: 1 },
        steps: 4,
        stepLen: 10,
        blendAngleAmt: 1,
        flattenAngle: 0,
        strokeWidth: 10,
        taper: 0.4,
        taperLen: 25,
        taperType: 'end',
    },
    animation: {
        animated: false,
        jitterRatio: 3,
        clumpAmt: 150,
        clumpScale: 0.15,
        strokesPerFrame: 100,
        rowStagger: 0.5,
        direction: 'up',
    },
    colors: {
        hue: 250,
        addHue: 180,
        lessSaturated: false,
    },
}
